--- #YAML:1.0
name:               App-s5pdf
version:            0.02
abstract:           Convert an S5 presentation to PDF
author:
    - Emmanuel Rodriguez <potyl@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cairo::GObject:  0
    Cwd:             0
    File::Basename:  0
    Getopt::Long:    0
    Glib:            0
    Gtk3:            0
    Gtk3::WebKit:    0
    Pod::Usage:      0
    URI:             0
resources:
    bugtracker:  https://github.com/potyl/perl-App-s5pdf/issues
    homepage:    https://github.com/potyl/perl-App-s5pdf
    repository:  https://github.com/potyl/perl-App-s5pdf
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
